package windows;

import commons.Student;
import commons.Book;
import commons.PseudoDatabase;
import java.time.LocalDate;
import java.util.stream.Collectors;

public class SelectedStudentBorrowedBooks extends javax.swing.JDialog {

    /**
     * Creates new form SelectedStudentBorrowedBooks
     * @param parent
     */
    private javax.swing.JFrame adminDashboard;
    private PseudoDatabase psDatabase;
    private Student selectedStudent;
    private Book selectedBook;
    
    public SelectedStudentBorrowedBooks(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        this.adminDashboard = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookTitleValueParentScrollPane = new javax.swing.JScrollPane();
        bookTitleValueTxtArea = new javax.swing.JTextArea();
        bookAuthorValueParentScrollPane = new javax.swing.JScrollPane();
        bookAuthorValueTxtArea = new javax.swing.JTextArea();
        bookCategoryValueLbl = new javax.swing.JLabel();
        borrowedBookListParentScrollPane = new javax.swing.JScrollPane();
        borrowedBookJList = new javax.swing.JList<>();
        resetBookListBttn = new javax.swing.JButton();
        dateBorrowedValueLbl = new javax.swing.JLabel();
        dueDateValueLbl = new javax.swing.JLabel();
        searchBorrowedBookLbl = new javax.swing.JLabel();
        searchBorrowedBookTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrowed Books");
        getContentPane().setLayout(null);

        bookTitleValueTxtArea.setEditable(false);
        bookTitleValueTxtArea.setColumns(20);
        bookTitleValueTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookTitleValueTxtArea.setLineWrap(true);
        bookTitleValueTxtArea.setRows(2);
        bookTitleValueTxtArea.setWrapStyleWord(true);
        bookTitleValueTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        bookTitleValueParentScrollPane.setViewportView(bookTitleValueTxtArea);

        getContentPane().add(bookTitleValueParentScrollPane);
        bookTitleValueParentScrollPane.setBounds(33, 74, 561, 85);

        bookAuthorValueParentScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        bookAuthorValueTxtArea.setEditable(false);
        bookAuthorValueTxtArea.setColumns(20);
        bookAuthorValueTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookAuthorValueTxtArea.setLineWrap(true);
        bookAuthorValueTxtArea.setRows(2);
        bookAuthorValueTxtArea.setWrapStyleWord(true);
        bookAuthorValueTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Author/s", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        bookAuthorValueParentScrollPane.setViewportView(bookAuthorValueTxtArea);

        getContentPane().add(bookAuthorValueParentScrollPane);
        bookAuthorValueParentScrollPane.setBounds(33, 170, 561, 85);

        bookCategoryValueLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookCategoryValueLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        bookCategoryValueLbl.setPreferredSize(new java.awt.Dimension(104, 83));
        getContentPane().add(bookCategoryValueLbl);
        bookCategoryValueLbl.setBounds(33, 266, 561, 101);

        borrowedBookJList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        borrowedBookJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        borrowedBookJList.addListSelectionListener((e) -> {
            if (!resetBookListBttn.isEnabled()) { resetBookListBttn.setEnabled(true); }
            selectedBook = psDatabase.getAllBooks().stream()
            .reduce(null, (sub, current) -> current.getTitle().equals(borrowedBookJList.getSelectedValue()) ? 
                current : sub);
            if (selectedBook != null) {
                bookTitleValueTxtArea.setText(selectedBook.getTitle());
                bookAuthorValueTxtArea.setText(selectedBook.getAuthor());
                bookCategoryValueLbl.setText(selectedBook.getCategory());
                dateBorrowedValueLbl.setText(selectedStudent.getBorrowAndDueInfo(selectedBook).getBorrowedDate().toString());
                dueDateValueLbl.setText(selectedStudent.getBorrowAndDueInfo(selectedBook).getDueDate().toString());
                if (dueDateValueLbl.getText().compareTo(LocalDate.now().toString()) < 0) {
                    dueDateValueLbl.setForeground(java.awt.Color.RED);
                    dueDateValueLbl.setToolTipText("This book is overdue");
                } else {
                    dueDateValueLbl.setForeground(java.awt.Color.BLACK);
                    dueDateValueLbl.setToolTipText("");
                }
            } else {
                bookTitleValueTxtArea.setText("");
                bookAuthorValueTxtArea.setText("");
                bookCategoryValueLbl.setText("");
                dateBorrowedValueLbl.setText("");
                dueDateValueLbl.setText("");
            }
        });
        borrowedBookListParentScrollPane.setViewportView(borrowedBookJList);

        getContentPane().add(borrowedBookListParentScrollPane);
        borrowedBookListParentScrollPane.setBounds(623, 74, 258, 560);

        resetBookListBttn.setBackground(new java.awt.Color(51, 204, 0));
        resetBookListBttn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resetBookListBttn.setForeground(new java.awt.Color(255, 255, 255));
        resetBookListBttn.setText("Reset Book List");
        resetBookListBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBookListBttnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBookListBttn);
        resetBookListBttn.setBounds(324, 602, 270, 32);

        dateBorrowedValueLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateBorrowedValueLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date Borrowed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        dateBorrowedValueLbl.setPreferredSize(new java.awt.Dimension(104, 83));
        getContentPane().add(dateBorrowedValueLbl);
        dateBorrowedValueLbl.setBounds(33, 378, 561, 101);

        dueDateValueLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dueDateValueLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Due Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        dueDateValueLbl.setPreferredSize(new java.awt.Dimension(104, 83));
        getContentPane().add(dueDateValueLbl);
        dueDateValueLbl.setBounds(33, 490, 561, 101);

        searchBorrowedBookLbl.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchBorrowedBookLbl.setText("Search Borrowed Book:");
        getContentPane().add(searchBorrowedBookLbl);
        searchBorrowedBookLbl.setBounds(440, 36, 179, 25);

        searchBorrowedBookTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBorrowedBookTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBorrowedBookTxtFldActionPerformed(evt);
            }
        });
        getContentPane().add(searchBorrowedBookTxtFld);
        searchBorrowedBookTxtFld.setBounds(623, 37, 258, 26);

        setSize(new java.awt.Dimension(950, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetBookListBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBookListBttnActionPerformed
        borrowedBookJList.setListData(selectedStudent
                .getBorrowedBooks().stream()
                .map(b -> b.getTitle())
                .collect(Collectors.toList())
                .toArray(new String[0])
        );
        searchBorrowedBookTxtFld.setText("");
    }//GEN-LAST:event_resetBookListBttnActionPerformed

    private void searchBorrowedBookTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBorrowedBookTxtFldActionPerformed
        if (!searchBorrowedBookTxtFld.getText().isEmpty()) {
            borrowedBookJList.setListData(selectedStudent.getBorrowedBooks()
                .stream()
                .filter(b -> b.getTitle().toLowerCase().contains(searchBorrowedBookTxtFld.getText().toLowerCase()))
                .map(b -> b.getTitle())
                .collect(Collectors.toList())
                .toArray(new String[0])
            );
        } else {
            resetBookListBttnActionPerformed(evt);
        }
        
    }//GEN-LAST:event_searchBorrowedBookTxtFldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelectedStudentBorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelectedStudentBorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelectedStudentBorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelectedStudentBorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(() -> {
//            //empty
//        });
//    }
    
    //custom methods
    protected void initializeStudentAndPsdatabase(Student st, PseudoDatabase ps) {
        this.psDatabase = ps;
        this.selectedStudent = st;
        
        borrowedBookJList.setListData(selectedStudent
                .getBorrowedBooks().stream()
                .map(b -> b.getTitle())
                .collect(Collectors.toList())
                .toArray(new String[0])
        );
        
        bookTitleValueTxtArea.setText("");
        bookAuthorValueTxtArea.setText("");
        bookCategoryValueLbl.setText("");
        dateBorrowedValueLbl.setText("");
        dueDateValueLbl.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookAuthorValueParentScrollPane;
    private javax.swing.JTextArea bookAuthorValueTxtArea;
    private javax.swing.JLabel bookCategoryValueLbl;
    private javax.swing.JScrollPane bookTitleValueParentScrollPane;
    private javax.swing.JTextArea bookTitleValueTxtArea;
    private javax.swing.JList<String> borrowedBookJList;
    private javax.swing.JScrollPane borrowedBookListParentScrollPane;
    private javax.swing.JLabel dateBorrowedValueLbl;
    private javax.swing.JLabel dueDateValueLbl;
    private javax.swing.JButton resetBookListBttn;
    private javax.swing.JLabel searchBorrowedBookLbl;
    private javax.swing.JTextField searchBorrowedBookTxtFld;
    // End of variables declaration//GEN-END:variables
}
