package windows;

import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

public class StartupForm extends javax.swing.JFrame {
    
    private StudentLogIn studentLogin;
    private AdminLogIn adminLogin;
    private StudentDashboard studentDashboard;
    private RegisterAdmin registerAdmin;
    private List<AdminDashboard> openAdminDashboards;
    
    /**
     * Creates new form StartupForm
     */
    public StartupForm() {
        initComponents();
        openAdminDashboards = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        bgImgLabel = new javax.swing.JLabel();
        welcomeToLbl = new javax.swing.JLabel();
        libSystemLbl = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        aboutBttn = new javax.swing.JButton();
        studentBttn = new javax.swing.JButton();
        adminBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Library Management System");
        setIconImage(new javax.swing.ImageIcon("C:\\Users\\Gelnn Spencre\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\resources\\librarySystemIcon.png").getImage()
        );
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgImgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/startupBgImg.jpg"))); // NOI18N
        layeredPane.add(bgImgLabel);
        bgImgLabel.setBounds(0, 0, 784, 461);

        welcomeToLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        welcomeToLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeToLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeToLbl.setText("LIBRARY");
        layeredPane.setLayer(welcomeToLbl, javax.swing.JLayeredPane.PALETTE_LAYER);
        layeredPane.add(welcomeToLbl);
        welcomeToLbl.setBounds(150, 150, 500, 60);

        libSystemLbl.setFont(welcomeToLbl.getFont());
        libSystemLbl.setForeground(welcomeToLbl.getForeground());
        libSystemLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libSystemLbl.setText("MANAGEMENT SYSTEM");
        layeredPane.setLayer(libSystemLbl, javax.swing.JLayeredPane.PALETTE_LAYER);
        layeredPane.add(libSystemLbl);
        libSystemLbl.setBounds(0, 220, 780, 60);

        getContentPane().add(layeredPane, java.awt.BorderLayout.CENTER);

        topPanel.setBackground(java.awt.Color.black);
        topPanel.setForeground(new java.awt.Color(255, 255, 255));

        aboutBttn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aboutBttn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBttn.setText("ABOUT");
        aboutBttn.setBorderPainted(false);
        aboutBttn.setContentAreaFilled(false);
        aboutBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutBttn.setFocusable(false);
        aboutBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutBttnMouseExited(evt);
            }
        });
        aboutBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBttnActionPerformed(evt);
            }
        });

        studentBttn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentBttn.setForeground(new java.awt.Color(255, 255, 255));
        studentBttn.setText("STUDENT");
        studentBttn.setBorderPainted(false);
        studentBttn.setContentAreaFilled(false);
        studentBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentBttn.setFocusable(false);
        studentBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentBttnMouseExited(evt);
            }
        });
        studentBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBttnActionPerformed(evt);
            }
        });

        adminBttn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        adminBttn.setForeground(new java.awt.Color(255, 255, 255));
        adminBttn.setText("ADMIN");
        adminBttn.setBorderPainted(false);
        adminBttn.setContentAreaFilled(false);
        adminBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminBttn.setFocusable(false);
        adminBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBttnMouseExited(evt);
            }
        });
        adminBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(aboutBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(adminBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentBttn)
                .addGap(23, 23, 23))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminBttn)
                    .addComponent(studentBttn)
                    .addComponent(aboutBttn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBttnMouseEntered
        aboutBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
    }//GEN-LAST:event_aboutBttnMouseEntered

    private void aboutBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBttnMouseExited
        aboutBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
    }//GEN-LAST:event_aboutBttnMouseExited

    private void adminBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBttnMouseEntered
        if (adminBttn.isEnabled()) {
            adminBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        }
    }//GEN-LAST:event_adminBttnMouseEntered

    private void adminBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBttnMouseExited
        adminBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
    }//GEN-LAST:event_adminBttnMouseExited

    private void studentBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBttnMouseEntered
        if (studentBttn.isEnabled()) {
            studentBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        }
    }//GEN-LAST:event_studentBttnMouseEntered

    private void studentBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentBttnMouseExited
        studentBttn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
    }//GEN-LAST:event_studentBttnMouseExited

    private void aboutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBttnActionPerformed
        new AboutDialog(this, true).setVisible(true);
    }//GEN-LAST:event_aboutBttnActionPerformed

    private void adminBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBttnActionPerformed
        this.registerAdmin = new RegisterAdmin();
        this.adminLogin = new AdminLogIn();
        if (registerAdmin.getPsdb().getAllAdmins().size() == 0) {
            JOptionPane.showMessageDialog(null, "The Library System currently has no registered Admin", "Library Management System", JOptionPane.INFORMATION_MESSAGE);
            registerAdmin.setStartForm(this);
            registerAdmin.setVisible(true);
            this.adminBttn.setEnabled(false);
        } else {
            this.adminLogin.setStartForm(this);
            this.adminLogin.setVisible(true);
            adminBttn.setEnabled(false);
        }
    }//GEN-LAST:event_adminBttnActionPerformed

    private void studentBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBttnActionPerformed
        this.studentLogin = new StudentLogIn();
        this.studentLogin.setStartForm(this);
        this.studentLogin.setVisible(true);
        studentBttn.setEnabled(false);
    }//GEN-LAST:event_studentBttnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (studentDashboard == null && openAdminDashboards.size() == 0) {
            System.exit(0);
            return;
        }
        if (studentDashboard != null) {
            if (studentDashboard.isVisible()) {
                JOptionPane.showMessageDialog(null, "Please log out all accounts first", "Library Management System", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (openAdminDashboards.size() > 0) {
            JOptionPane.showMessageDialog(null, "Please log out all accounts first", "Library Management System", JOptionPane.ERROR_MESSAGE);
            return;           
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupForm().setVisible(true);
            }
        });
    }
    
    protected javax.swing.JButton getStudentBttn() {
        return this.studentBttn;
    }
    
    protected javax.swing.JButton getAdminBttn() {
        return this.adminBttn;
    }
    
    protected void setStudentDashboard(StudentDashboard studentDashboard) {
        this.studentDashboard = studentDashboard;
    }
    
    protected void addOpenDashboard(AdminDashboard admBoard) {
        openAdminDashboards.add(admBoard);
    }
    
    protected void removeOpenDashboard(AdminDashboard admBoard) {
        openAdminDashboards.remove(admBoard);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBttn;
    private javax.swing.JButton adminBttn;
    private javax.swing.JLabel bgImgLabel;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel libSystemLbl;
    private javax.swing.JButton studentBttn;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeToLbl;
    // End of variables declaration//GEN-END:variables
}
